### PR TITLE
See if this fixes the Woods and Mires issue

### PR DESCRIPTION
**Pull request by Sunconure11**
Compiling the mod acts weird for me, so maybe you should try this

### CODE REVIEW

**Comment by Sunconure11** [comment]
Also ask around on the MMD and Minecraft World Gen Modding discords for further aid

**Comment by Sunconure11** [comment]
PR is ready.

**Comment by Sunconure11** [comment]
I would bump up how often herbs spawn a bit though.

**Comment by cScotPlay** [comment]
issues fixed in version 2.0.6

**Pull request closed without merging**
